import CrudPage from "@/components/dashboard/CrudPage";

const columns = [
  { key: "title", label: "Report" },
  { key: "type", label: "Type" },
  { key: "generatedBy", label: "Generated By" },
  { key: "date", label: "Date" },
  { key: "status", label: "Status", badge: true },
];

const fields = [
  { key: "title", label: "Report Title", required: true, placeholder: "e.g. Monthly Event Summary" },
  { key: "type", label: "Type", type: "select", options: ["Event Summary", "Attendance Report", "Registration Report", "Financial Report", "Department Report"] },
  { key: "generatedBy", label: "Generated By", placeholder: "Enter name" },
  { key: "date", label: "Date", type: "date" },
  { key: "status", label: "Status", type: "select", options: ["Completed", "Pending", "In Progress"] },
];

const data = [
  { title: "Monthly Event Summary - Feb 2026", type: "Event Summary", generatedBy: "System", date: "Mar 1, 2026", status: "Completed" },
  { title: "Attendance Report - Tech Summit", type: "Attendance Report", generatedBy: "Dr. Amit Verma", date: "Mar 5, 2026", status: "Completed" },
  { title: "Registration Analytics Q1 2026", type: "Registration Report", generatedBy: "System", date: "Mar 10, 2026", status: "In Progress" },
  { title: "Department-wise Participation", type: "Department Report", generatedBy: "Admin", date: "Mar 8, 2026", status: "Completed" },
];

export default function ReportsPage() {
  return <CrudPage title="Reports" description="View and generate reports" columns={columns} fields={fields} initialData={data} addLabel="Generate Report" />;
}
