export const roleSidebarItems = {
  "super_admin": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Colleges", icon: "Building", href: "/dashboard/colleges" },
    { title: "Branches", icon: "GitBranch", href: "/dashboard/branches" },
    { title: "Branch Admins", icon: "UserCog", href: "/dashboard/branch-admins" },
    { title: "Departments", icon: "Building2", href: "/dashboard/departments" },
    { title: "HODs", icon: "Users", href: "/dashboard/hods" },
    { title: "Event Categories", icon: "Tag", href: "/dashboard/categories" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
    { title: "Reports", icon: "BarChart3", href: "/dashboard/reports" },
    { title: "Queries / Support", icon: "HelpCircle", href: "/dashboard/support" },
    { title: "Activity Logs", icon: "ScrollText", href: "/dashboard/activity" },
    { title: "Notifications", icon: "Bell", href: "/dashboard/notifications" },
    { title: "Settings", icon: "Settings", href: "/dashboard/settings" },
  ],
  "admin": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Departments", icon: "Building2", href: "/dashboard/departments" },
    { title: "HODs", icon: "Users", href: "/dashboard/hods" },
    { title: "Faculty Members", icon: "GraduationCap", href: "/dashboard/faculty" },
    { title: "Batch", icon: "Layers", href: "/dashboard/batch" },
    { title: "Students", icon: "UserCheck", href: "/dashboard/students" },
    { title: "Events", icon: "Calendar", href: "/dashboard/events" },
    { title: "Event Registrations", icon: "ClipboardList", href: "/dashboard/registrations" },
    { title: "Approvals", icon: "CheckCircle", href: "/dashboard/approvals" },
    { title: "Event Venues", icon: "MapPin", href: "/dashboard/venues" },
    { title: "Reports", icon: "BarChart3", href: "/dashboard/reports" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
    { title: "Notifications", icon: "Bell", href: "/dashboard/notifications" },
  ],
  "hod": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Faculty Members", icon: "GraduationCap", href: "/dashboard/faculty" },
    { title: "Batch", icon: "Layers", href: "/dashboard/batch" },
    { title: "Students", icon: "UserCheck", href: "/dashboard/students" },
    { title: "Events", icon: "Calendar", href: "/dashboard/events" },
    { title: "Event Registrations", icon: "ClipboardList", href: "/dashboard/registrations" },
    { title: "Approvals", icon: "CheckCircle", href: "/dashboard/approvals" },
    { title: "Attendance", icon: "ListChecks", href: "/dashboard/attendance" },
    { title: "Certificates", icon: "Award", href: "/dashboard/certificates" },
    { title: "Reports", icon: "BarChart3", href: "/dashboard/reports" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
  ],
  "faculty": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Students", icon: "UserCheck", href: "/dashboard/students" },
    { title: "Events", icon: "Calendar", href: "/dashboard/events" },
    { title: "Event Registrations", icon: "ClipboardList", href: "/dashboard/registrations" },
    { title: "Attendance", icon: "ListChecks", href: "/dashboard/attendance" },
    { title: "Certificates", icon: "Award", href: "/dashboard/certificates" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
  ],
  "coordinator": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Events", icon: "Calendar", href: "/dashboard/events" },
    { title: "Event Registrations", icon: "ClipboardList", href: "/dashboard/registrations" },
    { title: "Attendance", icon: "ListChecks", href: "/dashboard/attendance" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
  ],
  "student": [
    { title: "Dashboard", icon: "LayoutDashboard", href: "/dashboard" },
    { title: "Events", icon: "Calendar", href: "/dashboard/events" },
    { title: "My Registrations", icon: "ClipboardList", href: "/dashboard/my-registrations" },
    { title: "My Participation", icon: "Trophy", href: "/dashboard/participation" },
    { title: "Certificates", icon: "Award", href: "/dashboard/certificates" },
    { title: "Announcements", icon: "Megaphone", href: "/dashboard/announcements" },
    { title: "Notifications", icon: "Bell", href: "/dashboard/notifications" },
    { title: "Support", icon: "HelpCircle", href: "/dashboard/support" },
    { title: "Profile", icon: "User", href: "/dashboard/profile" },
  ],
};

export const roleLabels = {
  "super_admin": "Super Admin",
  "admin": "Branch Admin",
  "hod": "HOD",
  "faculty": "Faculty",
  "coordinator": "Event Coordinator",
  "student": "Student",
};
